development:
  adapter: postgresql
  encoding: utf8
  database: price_index_choropleth_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: price_index_choropleth_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: price_index_choropleth_production
  pool: 5
