# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 429d996fd4c95ab855ec98293757359327b58e3f714c9a0f8feef51af10001e63452c5468944a47cae7168a7fc08dd4c5fb762ca1072e8759a141323c120fba7

test:
  secret_key_base: 854d6f0bfbd8f0aca4e24206ecd72a456f4fc12b76249692efef8905975583627270e5ddb40591dd02ec15147c5e297dec860af7fbf4eb756a1f47ddd53fda40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
